### ISSUE TITLE
Reblog missing when post is a link

### ISSUE THREAD

**Issue by sysco792** [jenevieveee/jkit#11]
When reblogging a "Link" post the reblog button does not appear unless you delete the comments on the post, even if no comment appears on the post. Options to reblog, queue and draft are there but the actual button to perform the action is gone. Also the preview of the post often appears out of alignment.

**Comment by jenevieveee** [comment]
Looks like issues with the .publink/.typelink post type.

.publink was not tested with ReblogGrid; only .pubtext and and .pubimage. Need to either fix or filter.
Example URL: https://jennie.bdsmlr.com/post/350056807

Planned for v0.3.

**Comment by jenevieveee** [comment]
Appears to be caused by the reblog blog on bottom tweak. Grid tweak is behaving.
There appear to be two  image_content divs on the link type post; adding grid-column: 1 fixes on firefox. Need to test on Chromium.

**Comment by jenevieveee** [comment]
Released v0.3.1
